import pickle

dict_replace = {
       'ANTIGUA & BARBUDA': 'ANTIGUA AND BARBUDA',
       'BAHAMAS': 'BAHAMAS, THE',
       'BOSNIA & HERZEGOVINA': 'BOSNIA AND HERZEGOVINA',
       'BRUNEI (DARUSSALAM)': 'BRUNEI DARUSSALAM',
       'CABO VERDE': 'CAPE VERDE',
       'CHINA': 'CHINA (MAINLAND)',
       'CONGO': 'CONGO, DEM. REP.',
       'COTE D IVOIRE': "COTE D'IVOIRE",
       'CZECH REPUBLIC': 'CZECHIA',
       'EGYPT': 'EGYPT, ARAB REP.',
       'FAEROE ISLANDS': 'FAROE ISLANDS',
       'FRANCE': 'FRANCE (INCLUDING MONACO)',
       'GAMBIA': 'GAMBIA, THE',
       'GUINEA BISSAU': 'GUINEA-BISSAU',
       'HONG KONG SAR, CHINA': 'HONG KONG SPECIAL ADMINSTRATIVE REGION OF CHINA',
       'IRAN, ISLAMIC REP.': 'ISLAMIC REPUBLIC OF IRAN',
       'ITALY': 'ITALY (INCLUDING SAN MARINO)',
       "KOREA, DEM. PEOPLE'S REP.": 'KOREA, REP.',
       'KYRGYZ REPUBLIC': 'KYRGYZSTAN',
       'LAO PDR': 'LAO PEOPLE S DEMOCRATIC REPUBLIC',
       'MACAO SAR, CHINA': 'MACAU SPECIAL ADMINSTRATIVE REGION OF CHINA',
       'MACEDONIA': 'NORTH MACEDONIA',
       'MYANMAR': 'MYANMAR (FORMERLY BURMA)',
       'SLOVAK REPUBLIC': 'SLOVAKIA',
       'ST. KITTS AND NEVIS': 'ST. KITTS-NEVIS',
       'ST. VINCENT & THE GRENADINES': 'ST. VINCENT AND THE GRENADINES',
       'TURKEY': 'TURKIYE',
       'UNITED STATES': 'UNITED STATES OF AMERICA',
       'VENEZUELA': 'VENEZUELA, RB',
       'VIET NAM': 'VIETNAM',
       'YEMEN': 'YEMEN, REP.'
}

with open('saved_dictionary.pkl', 'wb') as f:
    pickle.dump(dict_replace, f)


